webtalk_init -webtalk_dir D:/Documents/H2017/TFE4141 DDS1/Project/Vivfiles/RSA/project_1.sim/sim_1/behav/xsim.dir/RSACoreTestBench_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Nov 20 23:58:01 2017" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2017.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "1909853" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "10bc629d-bd95-4332-8ae2-262fa2f45646" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2e5568e20b9a4c90a0976c640f22f6d3" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "126" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-4710HQ CPU @ 2.50GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2494 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "2706760 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "2.06_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "13860_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2120733114 -regid "211403821_0_0_947" -xml D:/Documents/H2017/TFE4141 DDS1/Project/Vivfiles/RSA/project_1.sim/sim_1/behav/xsim.dir/RSACoreTestBench_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/Documents/H2017/TFE4141 DDS1/Project/Vivfiles/RSA/project_1.sim/sim_1/behav/xsim.dir/RSACoreTestBench_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/Documents/H2017/TFE4141 DDS1/Project/Vivfiles/RSA/project_1.sim/sim_1/behav/xsim.dir/RSACoreTestBench_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
